// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EvaluateClient is the client API for Evaluate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EvaluateClient interface {
	SetEvaluateInfo(ctx context.Context, in *EvaluateInfo, opts ...grpc.CallOption) (*EvaluateResult, error)
}

type evaluateClient struct {
	cc grpc.ClientConnInterface
}

func NewEvaluateClient(cc grpc.ClientConnInterface) EvaluateClient {
	return &evaluateClient{cc}
}

func (c *evaluateClient) SetEvaluateInfo(ctx context.Context, in *EvaluateInfo, opts ...grpc.CallOption) (*EvaluateResult, error) {
	out := new(EvaluateResult)
	err := c.cc.Invoke(ctx, "/evaluate.Evaluate/SetEvaluateInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvaluateServer is the server API for Evaluate service.
// All implementations must embed UnimplementedEvaluateServer
// for forward compatibility
type EvaluateServer interface {
	SetEvaluateInfo(context.Context, *EvaluateInfo) (*EvaluateResult, error)
	mustEmbedUnimplementedEvaluateServer()
}

// UnimplementedEvaluateServer must be embedded to have forward compatible implementations.
type UnimplementedEvaluateServer struct {
}

func (UnimplementedEvaluateServer) SetEvaluateInfo(context.Context, *EvaluateInfo) (*EvaluateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEvaluateInfo not implemented")
}
func (UnimplementedEvaluateServer) mustEmbedUnimplementedEvaluateServer() {}

// UnsafeEvaluateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvaluateServer will
// result in compilation errors.
type UnsafeEvaluateServer interface {
	mustEmbedUnimplementedEvaluateServer()
}

func RegisterEvaluateServer(s grpc.ServiceRegistrar, srv EvaluateServer) {
	s.RegisterService(&Evaluate_ServiceDesc, srv)
}

func _Evaluate_SetEvaluateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluateServer).SetEvaluateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evaluate.Evaluate/SetEvaluateInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluateServer).SetEvaluateInfo(ctx, req.(*EvaluateInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Evaluate_ServiceDesc is the grpc.ServiceDesc for Evaluate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Evaluate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evaluate.Evaluate",
	HandlerType: (*EvaluateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetEvaluateInfo",
			Handler:    _Evaluate_SetEvaluateInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evaluate.proto",
}
