// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: evaluate.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User       string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ProjectId  string `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TrainingId string `protobuf:"bytes,4,opt,name=training_id,json=trainingId,proto3" json:"training_id,omitempty"`
	Error      string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	AccessUrl  string `protobuf:"bytes,6,opt,name=access_url,json=accessUrl,proto3" json:"access_url,omitempty"`
}

func (x *EvaluateInfo) Reset() {
	*x = EvaluateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateInfo) ProtoMessage() {}

func (x *EvaluateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateInfo.ProtoReflect.Descriptor instead.
func (*EvaluateInfo) Descriptor() ([]byte, []int) {
	return file_evaluate_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvaluateInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *EvaluateInfo) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *EvaluateInfo) GetTrainingId() string {
	if x != nil {
		return x.TrainingId
	}
	return ""
}

func (x *EvaluateInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EvaluateInfo) GetAccessUrl() string {
	if x != nil {
		return x.AccessUrl
	}
	return ""
}

type EvaluateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EvaluateResult) Reset() {
	*x = EvaluateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResult) ProtoMessage() {}

func (x *EvaluateResult) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResult.ProtoReflect.Descriptor instead.
func (*EvaluateResult) Descriptor() ([]byte, []int) {
	return file_evaluate_proto_rawDescGZIP(), []int{1}
}

var File_evaluate_proto protoreflect.FileDescriptor

var file_evaluate_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x0c, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x55, 0x72, 0x6c, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x51, 0x0a, 0x08, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x65, 0x12, 0x45, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x18, 0x2e,
	0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_evaluate_proto_rawDescOnce sync.Once
	file_evaluate_proto_rawDescData = file_evaluate_proto_rawDesc
)

func file_evaluate_proto_rawDescGZIP() []byte {
	file_evaluate_proto_rawDescOnce.Do(func() {
		file_evaluate_proto_rawDescData = protoimpl.X.CompressGZIP(file_evaluate_proto_rawDescData)
	})
	return file_evaluate_proto_rawDescData
}

var file_evaluate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_evaluate_proto_goTypes = []interface{}{
	(*EvaluateInfo)(nil),   // 0: evaluate.EvaluateInfo
	(*EvaluateResult)(nil), // 1: evaluate.EvaluateResult
}
var file_evaluate_proto_depIdxs = []int32{
	0, // 0: evaluate.Evaluate.SetEvaluateInfo:input_type -> evaluate.EvaluateInfo
	1, // 1: evaluate.Evaluate.SetEvaluateInfo:output_type -> evaluate.EvaluateResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_evaluate_proto_init() }
func file_evaluate_proto_init() {
	if File_evaluate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_evaluate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_evaluate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evaluate_proto_goTypes,
		DependencyIndexes: file_evaluate_proto_depIdxs,
		MessageInfos:      file_evaluate_proto_msgTypes,
	}.Build()
	File_evaluate_proto = out.File
	file_evaluate_proto_rawDesc = nil
	file_evaluate_proto_goTypes = nil
	file_evaluate_proto_depIdxs = nil
}
