// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinetuneClient is the client API for Finetune service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinetuneClient interface {
	SetFinetuneInfo(ctx context.Context, in *FinetuneInfo, opts ...grpc.CallOption) (*FinetuneResult, error)
}

type finetuneClient struct {
	cc grpc.ClientConnInterface
}

func NewFinetuneClient(cc grpc.ClientConnInterface) FinetuneClient {
	return &finetuneClient{cc}
}

func (c *finetuneClient) SetFinetuneInfo(ctx context.Context, in *FinetuneInfo, opts ...grpc.CallOption) (*FinetuneResult, error) {
	out := new(FinetuneResult)
	err := c.cc.Invoke(ctx, "/finetune.Finetune/SetFinetuneInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinetuneServer is the server API for Finetune service.
// All implementations must embed UnimplementedFinetuneServer
// for forward compatibility
type FinetuneServer interface {
	SetFinetuneInfo(context.Context, *FinetuneInfo) (*FinetuneResult, error)
	mustEmbedUnimplementedFinetuneServer()
}

// UnimplementedFinetuneServer must be embedded to have forward compatible implementations.
type UnimplementedFinetuneServer struct {
}

func (UnimplementedFinetuneServer) SetFinetuneInfo(context.Context, *FinetuneInfo) (*FinetuneResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFinetuneInfo not implemented")
}
func (UnimplementedFinetuneServer) mustEmbedUnimplementedFinetuneServer() {}

// UnsafeFinetuneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinetuneServer will
// result in compilation errors.
type UnsafeFinetuneServer interface {
	mustEmbedUnimplementedFinetuneServer()
}

func RegisterFinetuneServer(s grpc.ServiceRegistrar, srv FinetuneServer) {
	s.RegisterService(&Finetune_ServiceDesc, srv)
}

func _Finetune_SetFinetuneInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinetuneInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinetuneServer).SetFinetuneInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finetune.Finetune/SetFinetuneInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinetuneServer).SetFinetuneInfo(ctx, req.(*FinetuneInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Finetune_ServiceDesc is the grpc.ServiceDesc for Finetune service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Finetune_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finetune.Finetune",
	HandlerType: (*FinetuneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetFinetuneInfo",
			Handler:    _Finetune_SetFinetuneInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finetune.proto",
}
