// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrainingClient is the client API for Training service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingClient interface {
	SetTrainingInfo(ctx context.Context, in *TrainingInfo, opts ...grpc.CallOption) (*TrainingResult, error)
}

type trainingClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingClient(cc grpc.ClientConnInterface) TrainingClient {
	return &trainingClient{cc}
}

func (c *trainingClient) SetTrainingInfo(ctx context.Context, in *TrainingInfo, opts ...grpc.CallOption) (*TrainingResult, error) {
	out := new(TrainingResult)
	err := c.cc.Invoke(ctx, "/training.Training/SetTrainingInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainingServer is the server API for Training service.
// All implementations must embed UnimplementedTrainingServer
// for forward compatibility
type TrainingServer interface {
	SetTrainingInfo(context.Context, *TrainingInfo) (*TrainingResult, error)
	mustEmbedUnimplementedTrainingServer()
}

// UnimplementedTrainingServer must be embedded to have forward compatible implementations.
type UnimplementedTrainingServer struct {
}

func (UnimplementedTrainingServer) SetTrainingInfo(context.Context, *TrainingInfo) (*TrainingResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTrainingInfo not implemented")
}
func (UnimplementedTrainingServer) mustEmbedUnimplementedTrainingServer() {}

// UnsafeTrainingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingServer will
// result in compilation errors.
type UnsafeTrainingServer interface {
	mustEmbedUnimplementedTrainingServer()
}

func RegisterTrainingServer(s grpc.ServiceRegistrar, srv TrainingServer) {
	s.RegisterService(&Training_ServiceDesc, srv)
}

func _Training_SetTrainingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).SetTrainingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/training.Training/SetTrainingInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).SetTrainingInfo(ctx, req.(*TrainingInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Training_ServiceDesc is the grpc.ServiceDesc for Training service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Training_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "training.Training",
	HandlerType: (*TrainingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTrainingInfo",
			Handler:    _Training_SetTrainingInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "training.proto",
}
